checksumBehavior: update

yarnPath: .yarn/releases/yarn-4.4.1.cjs

packageExtensions:
  hardhat-tracer@*:
    dependencies:
      "@nomicfoundation/ethereumjs-evm": "*"
      "@nomicfoundation/ethereumjs-tx": "*"
      "@nomicfoundation/ethereumjs-util": "*"
      "@nomicfoundation/ethereumjs-vm": "*"
      fs-extra: "*"
  wagmi@*:
    dependencies:
      "@tanstack/query-core": "*"
