checksumBehavior: update

packageExtensions:
  hardhat-tracer@*:
    dependencies:
      "@nomicfoundation/ethereumjs-evm": "*"
      "@nomicfoundation/ethereumjs-tx": "*"
      "@nomicfoundation/ethereumjs-util": "*"
      "@nomicfoundation/ethereumjs-vm": "*"
      fs-extra: "*"
  wagmi@*:
    dependencies:
      "@tanstack/query-core": "*"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
