name: Publish on NPM

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        required: true
        description: Type of version
        options:
          - patch
          - minor
          - major
          - prerelease
          - custom
      custom_version:
        type: string
        required: false
        description: Custom version (e.g., 1.0.0-unstable.1)

jobs:
  publish-to-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CD_GITHUB_APP_ID }}
          private-key: ${{ secrets.CD_GITHUB_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn

      - run: yarn install --immutable

      - name: Version and publish
        run: |
          if [ "${{ inputs.version }}" == "custom" ]; then
            if [ -z "${{ inputs.custom_version }}" ]; then
              echo "Error: Custom version is required when 'custom' is selected"
              exit 1
            fi
            yarn lerna version ${{ inputs.custom_version }} --no-git-tag-version --yes --force-publish
            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
            yarn lerna publish from-package --yes --dist-tag unstable
          else
            yarn lerna version ${{ inputs.version }} --no-private --conventional-commits --create-release github --generate-release-notes --yes
            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
            yarn run publish --yes
          fi
