name: Publish

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install

      # First, run versioning to have the correct version referenced in each package.json.
      # Limit concurrency to avoid semantic-release failing at pushing tags.
      - run: |
          pnpm -r --parallel -c exec "jq '.release = input.release' package.json ../../package.json > tmp.json && mv tmp.json package.json"
          pnpm -r --workspace-concurrency=1 --no-reporter-hide-prefix exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - if: github.ref_name == 'main'
        run: pnpm -r --parallel publish --no-git-checks --access public

      - if: github.ref_name == 'next'
        run: pnpm -r --parallel publish --no-git-checks --access public --tag next
