name: Release

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    # Skip build on `main` and `next` branches because it's already done in `publish`.
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next'

    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  publish:
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/next'

    needs:
      - lint
      - test

    uses: ./.github/workflows/publish.yml
    secrets: inherit