name: Push

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    uses: ./.github/workflows/build.yml

  vitest:
    uses: ./.github/workflows/vitest.yml

  release:
    needs:
      - lint
      - build
      - vitest

    uses: ./.github/workflows/semantic-release.yml
    secrets: inherit