name: Release

on:
  push:
    branches:
      - main
      - next

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  vitest:
    uses: ./.github/workflows/vitest.yml
    secrets: inherit

  release:
    needs:
      - build
      - vitest

    uses: ./.github/workflows/semantic-release.yml
    secrets: inherit